server:
  port: 8084

spring:
  application:
    name: exam-paper
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam_flow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.examflow: info
