server:
  port: 8090

spring:
  application:
    name: exam-message
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam_flow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
  mail:
    host: 127.0.0.1
    port: 25
    username: examflow@example.com
    password: change-me

# RocketMQ(通知事件消费)
rocketmq:
  name-server: 127.0.0.1:9876
  consumer:
    group: message-consumer

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.examflow: info
